use_frameworks!

platform :ios, '9.0'

target 'MyCocoaPodsLibrary_Example' do
  pod 'MyCocoaPodsLibrary', :path => '../'

  target 'MyCocoaPodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
